### ISSUE TITLE
Jupyter: Get familiarised with the environment

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/zenodo-jupyterlab-extension#1]
- [x] Learn how to spawn jupyter local session in your computer
- [x] Do the juoyter extension tutorial

**Comment by mrzengel** [comment]
I branched out from a previous commit on the side if you want to see the finished tutorial. It's just to show this task was done before I started reworking it to be designed for zenodo. After we take a look in the meeting, we can just discard it.
