### ISSUE TITLE
[Packaging] - Create a simple CI/CD script that tests the main branch builds correctly

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/zenodo-jupyterlab-extension#16]
- [x] Get started with GitHub Actions
 - [x] Create a **simple** CI workflow, based on the build action that was automatically created by `copier` when the project was initialised: lines 13-60 of https://github.com/vre-hub/zenodo-jupyterlab-extension/blob/100a48aa5f14d8985b548b2f80eb032f9a9bcbda/.github/workflows/build.yml#L13-L60

**Comment by garciagenrique** [comment]
https://github.com/vre-hub/zenodo-jupyterlab-extension/pull/17

CI is currently broken; have a look to the action's output and adapt the JS according to the errors

**Comment by mrzengel** [comment]
[the code](.github/workflows/build.yaml)
