### ISSUE TITLE
REST APIs: Get familiarised with Zenodo REST API

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/zenodo-jupyterlab-extension#3]
- [x] Open and account in zenodo.org
- [x] Follow the tutorial https://developers.zenodo.org/#introduction
- [x] Explore already created (Open Source) python libraries that interact with Zenodo
- [x] Create a small script that parses/returns all the entries within the  the `ESCAPE2020` [ Zenodo community](https://zenodo.org/communities/escape2020).
- [x] Create a small script that uploads a file/directory/package to [Sandbox Zenodo](https://sandbox.zenodo.org/) using your user token.

**Comment by mrzengel** [comment]
Just a comment: I got the upload to work, just went back and deleted the databases it made on sandbox because I didn't want to clutter it with a bunch of practice ones.

**Comment by mrzengel** [comment]
[https://github.com/vre-hub/zenodo-jupyterlab-extension/blob/dev/zenodo_test/escape_2020_test.py](url)
