### ISSUE TITLE
 [Preservation] Containerize extension

### ISSUE THREAD

**Issue by Soap2G** [vre-hub/zenodo-jupyterlab-extension#40]
```[tasklist]
### Tasks
- [ ] Build a docker image that spawns a jupyterlab environment with the Zenodo extension attached.
- [ ] Build a CI/CD pipeline that updates the image on the registry at each merged PR to main.
```
### Suggestions
Base layer for the Dockerfile: [here](https://hub.docker.com/u/jupyter)
Boilerplate for github action: [here](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages)

**Comment by garciagenrique** [comment]
Two suggestions for the github actions 
 - Reana jupyterlab project
 - https://github.com/vre-hub/environments/blob/main/.github/workflows/env-build.yaml#L71
