### ISSUE TITLE
[Frontend] Upload functionality from the extension

### ISSUE THREAD

**Issue by Soap2G** [vre-hub/zenodo-jupyterlab-extension#42]
Develop the upload tab.

Provide 2 ways of uploading:
- [x] Via a form with the necessary fields to be filled (based on https://zenodo.org/uploads/new)
- [ ] #52

**Comment by garciagenrique** [comment]
Task num 2 , i.e., Issue #52 marked as `Future enhancements`, therefore closing this issue
