### ISSUE TITLE
[REST APIs] - Choose a library to interact with Zenodo

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/zenodo-jupyterlab-extension#9]
- [ ] Get familiarised with the different Open Source existing libraries to interact with the Zenodo API
    - [ ] [zenodopy](https://github.com/lgloege/zenodopy)
    - [ ] [zenodo-client](https://github.com/cthoyt/zenodo-client)
    - [x] [eOSSR](https://gitlab.com/escape-ossr/eossr)
    - [ ] Any other Zenodo wrapper you might discover

- [x] Translate the 'fetch-communities' script into a script using the chosen library

- Set up few testing scripts with the chosen library
  - [x] Within all the examples, think and implement of a way to ask/request for the ZENODO user token
     - [ ] Think of a way to manage a return payload with +100 answers.
  - [x] Search and return any entries with software as a resource type
  - [x] Search and return entries with different file formats (`.txt`, and `.root`, for example)
  - [x] Search and return entries with medata file
     - [ ] #27

**Comment by mrzengel** [comment]
![Image](https://github.com/vre-hub/zenodo-jupyterlab-extension/assets/99219497/a47f8018-3a79-4258-ad31-893450bc3678)

Something we'll have to address in the future: there's a rate limit for the Zenodo REST API, so we can only get 100 records with each request. This shouldn't be too much of a problem, but something to keep in mind.

**Comment by mrzengel** [comment]
[Script that returns records with resource type "Software"](https://github.com/vre-hub/zenodo-jupyterlab-extension/blob/dev/zenodo_test/resource_type_script.py)
[Script that returns records with a specified file type](https://github.com/vre-hub/zenodo-jupyterlab-extension/blob/dev/zenodo_test/file-type_test.py)
[Script that returns records with `codemeta.json` file](https://github.com/vre-hub/zenodo-jupyterlab-extension/blob/dev/zenodo_test/metadata_test.py)

**Comment by garciagenrique** [comment]
> 
> Something we'll have to address in the future: there's a rate limit for the Zenodo REST API, so we can only get 100 records with each request. This shouldn't be too much of a problem, but something to keep in mind.

How does it look and how do you interact with a requests answer containing more than 100 (for example) entries ?

**Comment by garciagenrique** [comment]
`eOSSR` selected as the lib to interact with the Zenodo REST API. Added as requirements on [#29](https://github.com/vre-hub/zenodo-jupyterlab-extension/pull/29)
